# Generated by Django 4.1 on 2022-08-22 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Details', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='semister_number',
            new_name='semester_number',
        ),
    ]
