# Generated by Django 4.1 on 2022-08-25 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Details', '0004_alter_student_firstname'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='saroj',
            field=models.CharField(default=1992, max_length=10),
            preserve_default=False,
        ),
    ]
